### ISSUE TITLE
List is always empty

### ISSUE THREAD

**Issue by sw-dev-code** [jasonkinner/openvpn-stats#1]
Can you tell me why I'm always getting the empty list even when there is a connection in `openvpn-status.log` like you can see below:

```
TITLE,OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019
TIME,Fri Mar 26 11:54:08 2021,1616756048
HEADER,CLIENT_LIST,Common Name,Real Address,Virtual Address,Virtual IPv6 Address,Bytes Received,Bytes Sent,Connected Since,Connected Since (time_t),Username,Client ID,Peer ID
CLIENT_LIST,edge-01,62.4.63.1:38056,10.8.0.2,,7052,4264,Fri Mar 26 11:54:03 2021,1616756043,UNDEF,3,0
HEADER,ROUTING_TABLE,Virtual Address,Common Name,Real Address,Last Ref,Last Ref (time_t)
ROUTING_TABLE,10.8.0.2,edge-01,62.4.63.1:38056,Fri Mar 26 11:54:07 2021,1616756047
GLOBAL_STATS,Max bcast/mcast queue length,0
END
```

Thank you in advance.

**Comment by jasonkinner** [comment]
Please make sure you checked this line (line 3) in the script:
input_file=/var/log/openvpn/openvpn-status.log

Can you confirm the full path to your openvpn-status.log file?

Are you running OpenVPN Community (free) version?

**Comment by jasonkinner** [comment]
The proper openvpn-status.log file should look similar to this (from OpenVPN 2.5.0):

OpenVPN CLIENT LIST
Updated,Tue Mar 30 16:13:45 2021
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
phone-ccsupply-107,173.61.193.101:45088,1913559138,2255707542,Mon Jan 25 09:25:33 2021
phone-mrhandyman-203,68.83.107.227:56208,1034065163,1054000858,Fri Mar 12 12:44:42 2021
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
10.8.0.102,phone-ccsupply-107,173.61.193.101:45088,Tue Mar 30 16:13:44 2021
10.8.0.62,phone-mrhandyman-203,68.83.107.227:56208,Tue Mar 30 16:13:40 2021
GLOBAL STATS
Max bcast/mcast queue length,39
END
